-- MySQL Script generated by MySQL Workbench
-- Sat Nov  4 00:51:02 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema itweb_mvc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema itweb_mvc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `itweb_mvc` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `itweb_mvc` ;

-- -----------------------------------------------------
-- Table `itweb_mvc`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itweb_mvc`.`category` (
  `category_id` INT(11) NOT NULL,
  `category_name` VARCHAR(255) NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itweb_mvc`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itweb_mvc`.`product` (
  `product_id` BIGINT(20) NOT NULL,
  `product_name` VARCHAR(50) NULL,
  `product_image` VARCHAR(50) NULL,
  `product_price` DOUBLE NULL,
  `product_desc` LONGTEXT NULL,
  `category_id` INT(11) NOT NULL,
  PRIMARY KEY (`product_id`, `category_id`),
  INDEX `fk_product_category_idx` (`category_id` ASC),
  CONSTRAINT `fk_product_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `itweb_mvc`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itweb_mvc`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itweb_mvc`.`users` (
  `user_id` BIGINT(20) NOT NULL,
  `user_firstname` VARCHAR(45) NULL,
  `user_lastname` VARCHAR(45) NULL,
  `users_email` VARCHAR(45) NOT NULL,
  `user_pass` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itweb_mvc`.`bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itweb_mvc`.`bill` (
  `bill_id` BIGINT(20) NOT NULL,
  `total` DOUBLE NULL,
  `payment` VARCHAR(255) NULL,
  `address` LONGTEXT NULL,
  `date` TIMESTAMP(20) NULL,
  `user_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`bill_id`, `user_id`),
  INDEX `fk_bill_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_bill_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `itweb_mvc`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `itweb_mvc`.`bill_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itweb_mvc`.`bill_detail` (
  `bill_detail_id` BIGINT(20) NOT NULL,
  `price` DOUBLE NULL,
  `quantity` INT(11) NULL,
  `bill_id` BIGINT(20) NOT NULL,
  `product_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`bill_detail_id`, `bill_id`, `product_id`),
  INDEX `fk_bill_detail_bill1_idx` (`bill_id` ASC),
  INDEX `fk_bill_detail_product1_idx` (`product_id` ASC),
  CONSTRAINT `fk_bill_detail_bill1`
    FOREIGN KEY (`bill_id`)
    REFERENCES `itweb_mvc`.`bill` (`bill_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bill_detail_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `itweb_mvc`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
